// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NZWalks.API.Migrations.PostgreSQL
{
    [DbContext(typeof(NZWalksPostgreDbContext))]
    [Migration("20251114133949_InitialPostgreCreate")]
    partial class InitialPostgreCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5420d83f-e63e-4981-b768-d67935b9c7e1"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("494667ce-47b6-4544-9c8a-0fa7e4db7ff1"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("1cff7579-3a13-4fba-8d9c-1e22c9e57db1"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7503ec2d-3354-4c65-bfdc-b9727caf7dd5"),
                            Code = "NRB",
                            Name = "Nairobi",
                            RegionImageUrl = "https://example.com/images/nairobi.jpg"
                        },
                        new
                        {
                            Id = new Guid("94dbd6b3-31f2-48ed-b7e9-02f5e74a660d"),
                            Code = "MBA",
                            Name = "Mombasa",
                            RegionImageUrl = "https://example.com/images/mombasa.jpg"
                        },
                        new
                        {
                            Id = new Guid("0bb8403e-c4a6-410c-b2b1-117762a25b0d"),
                            Code = "KIS",
                            Name = "Kisumu",
                            RegionImageUrl = "https://example.com/images/kisumu.jpg"
                        },
                        new
                        {
                            Id = new Guid("5a46ef1b-f149-4be4-b627-0c5832128326"),
                            Code = "NKU",
                            Name = "Nakuru",
                            RegionImageUrl = "https://example.com/images/nakuru.jpg"
                        },
                        new
                        {
                            Id = new Guid("557fb860-ba91-46e2-b821-84433398319f"),
                            Code = "ELD",
                            Name = "Eldoret",
                            RegionImageUrl = "https://example.com/images/eldoret.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62e0c8ff-fba9-4059-9cbb-9a1e586cd13b"),
                            Description = "A beautiful walk to enjoy the sunset views.",
                            DifficultyId = new Guid("5420d83f-e63e-4981-b768-d67935b9c7e1"),
                            LengthInKm = 5.5,
                            Name = "Sunset Trail",
                            RegionId = new Guid("7503ec2d-3354-4c65-bfdc-b9727caf7dd5")
                        },
                        new
                        {
                            Id = new Guid("8d9ccf12-bcf2-4abe-9789-8ffe72636fcd"),
                            Description = "A refreshing walk along the coast.",
                            DifficultyId = new Guid("494667ce-47b6-4544-9c8a-0fa7e4db7ff1"),
                            LengthInKm = 8.1999999999999993,
                            Name = "Coastal Breeze",
                            RegionId = new Guid("94dbd6b3-31f2-48ed-b7e9-02f5e74a660d")
                        },
                        new
                        {
                            Id = new Guid("48e0242a-084f-4f75-b577-b7eca30a1b1a"),
                            Description = "A challenging walk around the lake.",
                            DifficultyId = new Guid("1cff7579-3a13-4fba-8d9c-1e22c9e57db1"),
                            LengthInKm = 10.0,
                            Name = "Lakeside Loop",
                            RegionId = new Guid("0bb8403e-c4a6-410c-b2b1-117762a25b0d")
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
